# New Section

In [2]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense, Dropout, BatchNormalization, Conv2D, MaxPool2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [3]:
#import data set
!git clone https://github.com/jordantangy/Movie-Posters-Dataset.git

Cloning into 'Movie-Posters-Dataset'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Total 7871 (delta 0), reused 2 (delta 0), pack-reused 7869
Receiving objects: 100% (7871/7871), 246.26 MiB | 61.67 MiB/s, done.
Checking out files: 100% (7868/7868), done.


In [4]:
data = pd.read_csv('/content/Movie-Posters-Dataset/Dataset/train.csv')
data.head()

Id                                Genre  ...  War  Western
0  tt0086425                  ['Comedy', 'Drama']  ...    0        0
1  tt0085549        ['Drama', 'Romance', 'Music']  ...    0        0
2  tt0086465                           ['Comedy']  ...    0        0
3  tt0086567               ['Sci-Fi', 'Thriller']  ...    0        0
4  tt0086034  ['Action', 'Adventure', 'Thriller']  ...    0        0

[5 rows x 27 columns]

In [5]:
pic_width = 350
pic_height = 350
X = []
for i in tqdm(range(int(data.shape[0]))):
  path = '/content/Movie-Posters-Dataset/Dataset/Images/'+ data['Id'][i] +'.jpg'
  img = image.load_img(path, target_size=(pic_width,pic_height,3))
  img = image.img_to_array(img)
  img = img/255.0
  X.append(img)

X = np.array(X)

100%|██████████| 7254/7254 [00:27<00:00, 260.07it/s]


In [14]:

y = data.drop(['Id','Genre'], axis = 1)
y = y.to_numpy()
print(y)

X_train, X_test , y_train, y_test = train_test_split(X, y , random_state = 0 , test_size = 0.15)
print(X_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[[[[0.98039216 1.         1.        ]
   [0.95686275 0.9764706  0.99215686]
   [0.9372549  0.95686275 0.972549  ]
   ...
   [0.90588236 0.95686275 0.9882353 ]
   [0.9137255  0.9647059  0.99607843]
   [0.92156863 0.972549   1.        ]]

  [[0.95686275 0.9764706  0.99215686]
   [0.93333334 0.9529412  0.96862745]
   [0.91764706 0.9372549  0.9529412 ]
   ...
   [0.8745098  0.9254902  0.95686275]
   [0.8784314  0.92941177 0.9607843 ]
   [0.88235295 0.93333334 0.9647059 ]]

  [[0.9529412  0.972549   0.9882353 ]
   [0.9372549  0.95686275 0.972549  ]
   [0.9254902  0.94509804 0.96862745]
   ...
   [0.87058824 0.9254902  0.9607843 ]
   [0.87058824 0.9254902  0.9607843 ]
   [0.8666667  0.92156863 0.95686275]]

  ...

  [[0.99215686 0.99215686 0.99215686]
   [0.99215686 0.99215686 0.99215686]
   [0.99215686 0.99215686 0.99215686]
   ...
   [1.         1.         1.        ]
   

In [13]:
y = data.drop(['Id','Genre'], axis = 1)
y = y.to_numpy()
print(y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
